# Generated by Django 4.1.4 on 2023-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
