# Generated by Django 4.1.4 on 2023-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoapp', '0002_fondo_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fondo',
            name='total',
        ),
    ]
