# Generated by Django 4.1.2 on 2023-01-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoapp', '0004_delete_fondobanco'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
    ]
