# Generated by Django 4.1.2 on 2023-01-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancoapp', '0005_fondobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='cuotasPorPagar',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
